---
# This playbook deploys bioinformatics server

- name: apply common configurations to all nodes
  hosts: webserver
  remote_user: ubuntu
  roles:
          - make_sw_guy
          - common

  become: true

- name: set up bioinformatiky tools
  hosts: bioinformatics
  remote_user: "{{ sw_installer }}"
  roles:
          - bio_tools

- name: configure and deploy webserver
  hosts: webserver
  remote_user: ubuntu

  roles:
          - nginx 
  become: true

- name: set up interactive server
  hosts: interactive
  remote_user: ubuntu

  roles:
          - interactive 
  become: true
